### ISSUE TITLE
这个是自动打开吗，需要一直连接电脑吗？

### ISSUE THREAD

**Issue by chenerg** [elliot-bia/AACO_ADB_Auto_Clock_with_OCR#1]
想问作者几个问题：
1. 这个能设置时间自动打卡吗？
2. 这个是需要一直连接电脑，通过定时启动电脑命令连接手机打开吗？

**Comment by Adam-Zhong** [comment]
1、一般是设置crontab进行定时执行
2、是的，可以通过usb或者WiFi进行打卡，需要24h不停机的电脑。

**Comment by chenerg** [comment]
多谢
